### ISSUE TITLE
Changing image tagging from 7 chars to 8 chars of the commit sha

### ISSUE THREAD

**Issue by amaissen** [SwissDataScienceCenter/renku-ui#1951]
## Motivation

Currently images are tagged as 

`<registry>:<first 7 chars of commit sha>`

If there is no specific reason to use the first 7 chars for tagging, I suggest to use the first 8 chars to be consistent with GitLabs CI variable [CI_COMMIT_SHORT_SHA](https://docs.gitlab.com/ee/ci/variables/#list-all-environment-variables). This would easily allow to use the image in subsequent stages of the GitLabs's CI/CD pipeline. See following [example](https://renkulab.io/gitlab/ci-example/ci-renku-pipeline/-/blob/master/.gitlab-ci.yml#L22), where this improvement avoids building the image twice. I'm not aware of any method in GitLab that allows to choose the docker image dynamically using some shell logic. 

## Proposal

I suggest to start at code [line](https://github.com/SwissDataScienceCenter/renku-ui/blob/ec155aa8c302018aa092eea64ed5771240bc3d1c/client/src/notebooks/Notebooks.state.js#L1145). Change

`const commitShortSha = expectedTarget.substring(0, 7);`

to 

`const commitShortSha = expectedTarget.substring(0, 8);`

This changes would then require to update the templates created by `renku init`, i.e the build phase in CI/CD pipeline that builds the docker image. This would then look as following.

```
image_build:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN http://$CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  tags:
    - image-build
```

Since I do not know the repository, I'm not aware of any other changes expect changes to unit tests.
