### ISSUE TITLE
Project Showcase

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#2747]
## Motivation

Add an optional section containing showcase projects to the landing page. Issue will be updated with design when available. 

## Implementation Details

We should update the configuration for this feature in `helm-chart/renku-ui/values.yaml` to be:

```
  homepage:
    custom:
      # If you want to enable a custom content on the homepage, you can enable it and provide content here
      enabled: false
      ...
    # Projects to highlight on the homepage
    showcase:
      enabled: false
      projects: 
        - identifier: [project1 identifier]
        - identifier: [project2 identifier]
```

Supersedes #1932
