### ISSUE TITLE
Use renku service to create project

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#703]
# Description

Projects are currently autonomously created in the UI. We should use the renku service to create projects to remove code duplication between the UI and backend and ensure uniform semantics

**Comment by lorenzo-cavazzi** [comment]
The PR for creating the new endpoint in the core service is almost ready SwissDataScienceCenter/renku-python#1287. That requires a small re-work of the `new project` page since we can't use the endpoint for GitLab specific settings that are not stored in the repository (e.g. visibility and description)

**Comment by lorenzo-cavazzi** [comment]
Here is my proposal

For the `description` field, I suggest to drop the current one and use the `description` [implemented in the templates](https://github.com/SwissDataScienceCenter/renku-project-template/tree/master/python-minimal#-name-) -- adjusted if necessary. This requires to change the projects list to avoid showing the `No description available` label to something similar to GitLab.

<kbd><img src="https://user-images.githubusercontent.com/43481553/83043267-f06a3780-a042-11ea-8b79-fd61ad922236.png" /></kbd>

For the visibility, I would leave the dropdown as it is now and invoke the GitLab API once the project is created, along with the KG API for indexing the project (transparent to the user).

We have a lot of extra flexibility on how to chose the repository/repositories to fetch the templates from, and we want to support more than 1 repo (see #641).
I would allow the admins to personalize this page from the [value file](https://github.com/SwissDataScienceCenter/renku-ui/blob/cb074bd8617e61a20f8352f07758b2dcaafddcb7/helm-chart/renku-ui/values.yaml#L61) by changing the `templateRepository` to allow:
1. providing more repositories
2. deciding if users can get templates from custom repositories

This is a stub of the values

```
templates:
  custom: true
  repositories:
   - url: https://github.com/SwissDataScienceCenter/renku-project-template
     ref: 0.1.11
     prefix: Renku
   - url: https://github.com/lorenzo.cavazzi.tech/renku-project-template
     ref: master
     prefix: OpenLab
```

In the UI, I suggest to split the project creation into 2 steps:
1. Select template
![Screenshot_20200527_174459](https://user-images.githubusercontent.com/43481553/83043639-65d60800-a043-11ea-9f19-d9fcf5f70e86.png)
2. Specify project data
![Screenshot_20200527_174433](https://user-images.githubusercontent.com/43481553/83043599-5a82dc80-a043-11ea-874b-1a8907e3f7cf.png)

We may want to add a recap page with a `Confirm` button as a 3rd step.
